// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HDP.Persistence.Migrations
{
//     [DbContext(typeof(HDPContext))]
//     partial class HDPContextModelSnapshot : ModelSnapshot
//     {
//         protected override void BuildModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder
//                 .HasAnnotation("ProductVersion", "6.0.1")
//                 .HasAnnotation("Relational:MaxIdentifierLength", 63);
//
//             NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
//
//             modelBuilder.Entity("HDP.Domain.Models.Caminhao", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("uuid")
//                         .HasDefaultValueSql("uuid_generate_v4()");
//
//                     b.Property<int>("ClienteId")
//                         .HasColumnType("uuid");
//
//                     b.Property<string>("PlacaCaminhao")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.Property<int>("TipoCaminhaoId")
//                         .HasColumnType("uuid");
//
//                     b.HasKey("Id");
//
//                     b.HasIndex("ClienteId");
//
//                     b.HasIndex("TipoCaminhaoId");
//
//                     b.ToTable("Caminhoes");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Cliente", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("uuid")
//                         .HasDefaultValueSql("uuid_generate_v4()");
//
//                     b.Property<string>("Cpf")
//                         .HasColumnType("text");
//
//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.Property<string>("NomeNormalizado")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.HasKey("Id");
//
//                     b.ToTable("Clientes");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Constantes.AdicionaisVenda", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("uuid")
//                         .HasDefaultValueSql("uuid_generate_v4()");
//
//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.HasKey("Id");
//
//                     b.ToTable("AdicionaisVendas");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Constantes.TipoCaminhao", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("uuid")
//                         .HasDefaultValueSql("uuid_generate_v4()");
//
//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.HasKey("Id");
//
//                     b.ToTable("TiposCaminhoes");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Constantes.TipoPagamento", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("uuid")
//                         .HasDefaultValueSql("uuid_generate_v4()");
//
//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.HasKey("Id");
//
//                     b.ToTable("TiposPagamentos");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Material", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("uuid")
//                         .HasDefaultValueSql("uuid_generate_v4()");
//
//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.Property<float>("Preco")
//                         .HasColumnType("real");
//
//                     b.Property<int>("TipoCaminhaoId")
//                         .HasColumnType("uuid");
//
//                     b.HasKey("Id");
//
//                     b.HasIndex("TipoCaminhaoId");
//
//                     b.ToTable("Materiais");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Venda", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("uuid")
//                         .HasDefaultValueSql("uuid_generate_v4()");
//
//                     b.Property<int>("AdicionaisVendaId")
//                         .HasColumnType("uuid");
//
//                     b.Property<int>("CaminhaoId")
//                         .HasColumnType("uuid");
//
//                     b.Property<int>("ClienteId")
//                         .HasColumnType("uuid");
//
//                     b.Property<DateTime>("DataVenda")
//                         .HasColumnType("timestamp with time zone");
//
//                     b.Property<int>("MaterialId")
//                         .HasColumnType("uuid");
//
//                     b.Property<int>("TipoPagamentoId")
//                         .HasColumnType("uuid");
//
//                     b.Property<float>("Valor")
//                         .HasColumnType("real");
//
//                     b.HasKey("Id");
//
//                     b.HasIndex("AdicionaisVendaId");
//
//                     b.HasIndex("CaminhaoId");
//
//                     b.HasIndex("ClienteId");
//
//                     b.HasIndex("MaterialId");
//
//                     b.HasIndex("TipoPagamentoId");
//
//                     b.ToTable("Vendas");
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                 {
//                     b.Property<string>("Id")
//                         .HasColumnType("text");
//
//                     b.Property<string>("ConcurrencyStamp")
//                         .IsConcurrencyToken()
//                         .HasColumnType("text");
//
//                     b.Property<string>("Name")
//                         .HasMaxLength(256)
//                         .HasColumnType("character varying(256)");
//
//                     b.Property<string>("NormalizedName")
//                         .HasMaxLength(256)
//                         .HasColumnType("character varying(256)");
//
//                     b.HasKey("Id");
//
//                     b.HasIndex("NormalizedName")
//                         .IsUnique()
//                         .HasDatabaseName("RoleNameIndex");
//
//                     b.ToTable("AspNetRoles", (string)null);
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("integer");
//
//                     NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
//
//                     b.Property<string>("ClaimType")
//                         .HasColumnType("text");
//
//                     b.Property<string>("ClaimValue")
//                         .HasColumnType("text");
//
//                     b.Property<string>("RoleId")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.HasKey("Id");
//
//                     b.HasIndex("RoleId");
//
//                     b.ToTable("AspNetRoleClaims", (string)null);
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
//                 {
//                     b.Property<string>("Id")
//                         .HasColumnType("text");
//
//                     b.Property<int>("AccessFailedCount")
//                         .HasColumnType("integer");
//
//                     b.Property<string>("ConcurrencyStamp")
//                         .IsConcurrencyToken()
//                         .HasColumnType("text");
//
//                     b.Property<string>("Discriminator")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.Property<string>("Email")
//                         .HasMaxLength(256)
//                         .HasColumnType("character varying(256)");
//
//                     b.Property<bool>("EmailConfirmed")
//                         .HasColumnType("boolean");
//
//                     b.Property<bool>("LockoutEnabled")
//                         .HasColumnType("boolean");
//
//                     b.Property<DateTimeOffset?>("LockoutEnd")
//                         .HasColumnType("timestamp with time zone");
//
//                     b.Property<string>("NormalizedEmail")
//                         .HasMaxLength(256)
//                         .HasColumnType("character varying(256)");
//
//                     b.Property<string>("NormalizedUserName")
//                         .HasMaxLength(256)
//                         .HasColumnType("character varying(256)");
//
//                     b.Property<string>("PasswordHash")
//                         .HasColumnType("text");
//
//                     b.Property<string>("PhoneNumber")
//                         .HasColumnType("text");
//
//                     b.Property<bool>("PhoneNumberConfirmed")
//                         .HasColumnType("boolean");
//
//                     b.Property<string>("SecurityStamp")
//                         .HasColumnType("text");
//
//                     b.Property<bool>("TwoFactorEnabled")
//                         .HasColumnType("boolean");
//
//                     b.Property<string>("UserName")
//                         .HasMaxLength(256)
//                         .HasColumnType("character varying(256)");
//
//                     b.HasKey("Id");
//
//                     b.HasIndex("NormalizedEmail")
//                         .HasDatabaseName("EmailIndex");
//
//                     b.HasIndex("NormalizedUserName")
//                         .IsUnique()
//                         .HasDatabaseName("UserNameIndex");
//
//                     b.ToTable("AspNetUsers", (string)null);
//
//                     b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("integer");
//
//                     NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
//
//                     b.Property<string>("ClaimType")
//                         .HasColumnType("text");
//
//                     b.Property<string>("ClaimValue")
//                         .HasColumnType("text");
//
//                     b.Property<string>("UserId")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.HasKey("Id");
//
//                     b.HasIndex("UserId");
//
//                     b.ToTable("AspNetUserClaims", (string)null);
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                 {
//                     b.Property<string>("LoginProvider")
//                         .HasColumnType("text");
//
//                     b.Property<string>("ProviderKey")
//                         .HasColumnType("text");
//
//                     b.Property<string>("ProviderDisplayName")
//                         .HasColumnType("text");
//
//                     b.Property<string>("UserId")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.HasKey("LoginProvider", "ProviderKey");
//
//                     b.HasIndex("UserId");
//
//                     b.ToTable("AspNetUserLogins", (string)null);
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                 {
//                     b.Property<string>("UserId")
//                         .HasColumnType("text");
//
//                     b.Property<string>("RoleId")
//                         .HasColumnType("text");
//
//                     b.HasKey("UserId", "RoleId");
//
//                     b.HasIndex("RoleId");
//
//                     b.ToTable("AspNetUserRoles", (string)null);
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                 {
//                     b.Property<string>("UserId")
//                         .HasColumnType("text");
//
//                     b.Property<string>("LoginProvider")
//                         .HasColumnType("text");
//
//                     b.Property<string>("Name")
//                         .HasColumnType("text");
//
//                     b.Property<string>("Value")
//                         .HasColumnType("text");
//
//                     b.HasKey("UserId", "LoginProvider", "Name");
//
//                     b.ToTable("AspNetUserTokens", (string)null);
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Usuario.User", b =>
//                 {
//                     b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");
//
//                     b.Property<string>("FullName")
//                         .IsRequired()
//                         .HasColumnType("text");
//
//                     b.HasDiscriminator().HasValue("User");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Caminhao", b =>
//                 {
//                     b.HasOne("HDP.Domain.Models.Cliente", "Cliente")
//                         .WithMany("Caminhoes")
//                         .HasForeignKey("ClienteId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.HasOne("HDP.Domain.Models.Constantes.TipoCaminhao", "TipoCaminhao")
//                         .WithMany("Caminhoes")
//                         .HasForeignKey("TipoCaminhaoId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.Navigation("Cliente");
//
//                     b.Navigation("TipoCaminhao");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Material", b =>
//                 {
//                     b.HasOne("HDP.Domain.Models.Constantes.TipoCaminhao", "TipoCaminhao")
//                         .WithMany("Materiais")
//                         .HasForeignKey("TipoCaminhaoId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.Navigation("TipoCaminhao");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Venda", b =>
//                 {
//                     b.HasOne("HDP.Domain.Models.Constantes.AdicionaisVenda", "AdicionaisVenda")
//                         .WithMany("Vendas")
//                         .HasForeignKey("AdicionaisVendaId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.HasOne("HDP.Domain.Models.Caminhao", "Caminhao")
//                         .WithMany("Vendas")
//                         .HasForeignKey("CaminhaoId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.HasOne("HDP.Domain.Models.Cliente", "Cliente")
//                         .WithMany("Vendas")
//                         .HasForeignKey("ClienteId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.HasOne("HDP.Domain.Models.Material", "Material")
//                         .WithMany("Vendas")
//                         .HasForeignKey("MaterialId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.HasOne("HDP.Domain.Models.Constantes.TipoPagamento", "TipoPagamento")
//                         .WithMany("Vendas")
//                         .HasForeignKey("TipoPagamentoId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.Navigation("AdicionaisVenda");
//
//                     b.Navigation("Caminhao");
//
//                     b.Navigation("Cliente");
//
//                     b.Navigation("Material");
//
//                     b.Navigation("TipoPagamento");
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                         .WithMany()
//                         .HasForeignKey("RoleId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                         .WithMany()
//                         .HasForeignKey("RoleId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });
//
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Caminhao", b =>
//                 {
//                     b.Navigation("Vendas");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Cliente", b =>
//                 {
//                     b.Navigation("Caminhoes");
//
//                     b.Navigation("Vendas");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Constantes.AdicionaisVenda", b =>
//                 {
//                     b.Navigation("Vendas");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Constantes.TipoCaminhao", b =>
//                 {
//                     b.Navigation("Caminhoes");
//
//                     b.Navigation("Materiais");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Constantes.TipoPagamento", b =>
//                 {
//                     b.Navigation("Vendas");
//                 });
//
//             modelBuilder.Entity("HDP.Domain.Models.Material", b =>
//                 {
//                     b.Navigation("Vendas");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
}
